export type Locale = "en" | "ko" | "vi" | "fr" | "hi";

export const LOCALES: { code: Locale; label: string; flag: string }[] = [
  { code: "en", label: "English", flag: "🇺🇸" },
  { code: "ko", label: "한국어", flag: "🇰🇷" },
  { code: "vi", label: "Tiếng Việt", flag: "🇻🇳" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "hi", label: "हिन्दी", flag: "🇮🇳" },
];

export type T = {
  // Nav / common
  home: string;
  connecting: string;
  back: string;
  close: string;
  save: string;
  next: string;
  continueBtn: string;

  // Install PWA
  installApp: string;
  installIosHint: string;
  alreadyInstalled: string;

  // Home
  tagline: string;
  getStarted: string;
  howToPlay: string;
  joinRoom: string;

  // Lobby
  gameConditions: string;
  step1Group: string;
  step1Solo: string;
  solo: string;
  group: string;
  players: string;
  editParticipants: string;
  hostLabel: string;
  continueToGameType: string;

  // Genre
  step2: string;

  // Difficulty
  step3: string;
  writingRound: string;
  creatingImages: (done: number, total: number) => string;
  startGame: string;

  // Game screen
  passage: string;
  roundNotesTitle: string;
  note1: string;
  note2: string;
  note3: string;
  view3d: string;
  maze2d: string;
  clueKeywords: string;
  possibleAnswers: string;
  activity: string;
  lobbyBtn: string;
  bonusKeywords: string;
  additionalRevealed: string;
  finalRevealed: string;
  think: string;
  nextKeywordIn: string;
  bonusKeywordExcl: string;
  finalKeywordExcl: string;
  giveup: string;

  // Exit modal
  exitGameTitle: string;
  leaveConfirm: string;
  stay: string;
  leaveGame: string;

  // End modal
  noWinner: string;
  teamWins: (n: number) => string;
  playerWins: (name: string) => string;
  winner: string;
  newGame: string;

  // Play page — join
  joinRoomTitle: string;
  yourName: string;
  join: string;

  // Play page — lobby / genre / difficulty wait
  waitingForHost: string;
  playersInRoom: (n: number) => string;
  soloMode: string;
  groupMode: string;
  hostChoosingType: string;
  hostChoosingDiff: string;
  selectedLabel: (name: string) => string;

  // Play page — game
  yourFeed: string;
  teamFeed: string;
  askQuestion: string;
  questionPlaceholder: string;
  askQuestionBtn: string;
  attemptAnswer: string;
  howToAnswer: string;
  howToAnswerLine1: string;
  howToAnswerLine2: string;
  howToAnswerLine3: string;
  answerPlaceholder: string;
  attemptAnswerBtn: string;
  briefing: string;
  pts: string;

  // QR Scanner
  scanTitle: string;
  startingCamera: string;
  pointAtQR: string;
  cameraPermissionError: string;
  cameraStartError: string;
  orEnterCode: string;

  // Participants modal
  editParticipantsTitle: string;

  // How to play
  iUnderstand: string;
  howToPlayStep: (step: number, total: number) => string;
  howToPlayDesc1: string;
  soloCardTitle: string;
  soloCardDesc: string;
  groupCardTitle: string;
  groupCardDesc: string;
  howToPlayDesc2: string;
  howToPlayDesc3: string;
  morePts: string;
  howToPlayDesc4: string;
  readyTitle: string;
  readyDesc: string;

  // Genre display names + descriptions
  genreRiddles: string;
  genreRiddlesDesc: string;
  genreGuess: string;
  genreGuessDesc: string;
  genreVisualMatch: string;
  genreVisualMatchDesc: string;
  genreNumberToLetter: string;
  genreNumberToLetterDesc: string;

  // Difficulty labels + taglines
  diffEasy: string;
  diffEasyTagline: string;
  diffMedium: string;
  diffMediumTagline: string;
  diffHard: string;
  diffHardTagline: string;
  diffChallenger: string;
  diffChallengerTagline: string;
};

const en: T = {
  home: "← Home",
  connecting: "Connecting…",
  back: "Back",
  close: "Close",
  save: "Save",
  next: "Next",
  continueBtn: "Continue",

  installApp: "Install App",
  installIosHint: "Tap Share → Add to Home Screen",
  alreadyInstalled: "Installed ✓",

  tagline: "Who is ready to take the crown?",
  getStarted: "Get Started",
  howToPlay: "How to play",
  joinRoom: "Join a Room",

  gameConditions: "Game Conditions",
  step1Group: "Step 1: choose whether this round is solo or group play, then invite players into the room.",
  step1Solo: "Step 1: solo mode selected — no other players needed. Continue to choose the game type.",
  solo: "Solo",
  group: "Group",
  players: "Players",
  editParticipants: "Edit Participants",
  hostLabel: "(host)",
  continueToGameType: "Continue to Game Type",

  step2: "Step 2: choose the kind of game you want to play.",

  step3: "Step 3: choose the difficulty level, then start the round.",
  writingRound: "Writing the round with OpenAI",
  creatingImages: (done, total) => `Creating the images with OpenAI (${done} / ${total})`,
  startGame: "Start Game",

  passage: "Passage",
  roundNotesTitle: "Round Notes",
  note1: "All passages and images for this round are generated by the OpenAI API.",
  note2: "Whoever has more points wins the game.",
  note3: "Ask a question if you want a hint, but it costs 1 point.",
  view3d: "3D View",
  maze2d: "2D Maze",
  clueKeywords: "Clue Keywords",
  possibleAnswers: "Possible Answers",
  activity: "Activity",
  lobbyBtn: "Lobby",
  bonusKeywords: "Bonus keywords",
  additionalRevealed: "Additional keyword revealed",
  finalRevealed: "Final keyword revealed",
  think: "Think",
  nextKeywordIn: "Next keyword in",
  bonusKeywordExcl: "Bonus keyword!",
  finalKeywordExcl: "Final keyword!",
  giveup: "I have no idea, cuckoo",

  exitGameTitle: "Exit game",
  leaveConfirm: "Are you sure you want to leave the game?",
  stay: "Stay",
  leaveGame: "Leave the Game",

  noWinner: "No winner",
  teamWins: (n) => `Team ${n} wins!`,
  playerWins: (name) => `${name} wins!`,
  winner: "Winner",
  newGame: "New Game",

  joinRoomTitle: "Join Room",
  yourName: "Your name",
  join: "Join",

  waitingForHost: "Waiting for host",
  playersInRoom: (n) => `${n} players in room`,
  soloMode: "Solo mode",
  groupMode: "Group mode",
  hostChoosingType: "Host is choosing the game type…",
  hostChoosingDiff: "Host is choosing the difficulty…",
  selectedLabel: (name) => `Selected: ${name}`,

  yourFeed: "Your feed",
  teamFeed: "Team feed",
  askQuestion: "Ask a question",
  questionPlaceholder: "What would you like to know?",
  askQuestionBtn: "Ask question (-1 pt)",
  attemptAnswer: "Attempt an answer",
  howToAnswer: "How to answer",
  howToAnswerLine1: "Give your best answer using the passage, clues, and any revealed keywords.",
  howToAnswerLine2: "For number-to-letter and guess rounds, compare your answer with the choices carefully.",
  howToAnswerLine3: "For visual-match rounds, use the labeled maze to support your call.",
  answerPlaceholder: "Type the answer you want to submit",
  attemptAnswerBtn: "Attempt answer",
  briefing: "Briefing",
  pts: "pts",

  scanTitle: "Scan Room QR Code",
  startingCamera: "Starting camera…",
  pointAtQR: "Point at the QR code on the host screen",
  cameraPermissionError: "Camera permission denied. Please allow camera access and try again.",
  cameraStartError: "Could not start camera. Make sure you are on HTTPS or localhost.",
  orEnterCode: "Or enter room code",

  editParticipantsTitle: "Edit Participants",

  iUnderstand: "I understand",
  howToPlayStep: (step, total) => `How to Play — ${step} / ${total}`,
  howToPlayDesc1: "You can play by yourself, matched with AI or other players who are online, or you can play as a group. This is the mode selection step.",
  soloCardTitle: "Solo",
  soloCardDesc: "Go alone and chase the crown on your own pace.",
  groupCardTitle: "Group",
  groupCardDesc: "Talk it through together and see who reads the clues best.",
  howToPlayDesc2: "Next, you choose the kind of game you want to play: riddles, guess, visual-maze match, number-to-letter conversion, and more.",
  howToPlayDesc3: "Then you choose the level of challenge you want: easy, medium, hard, or challenger.",
  morePts: "Whoever has more points wins the game.",
  howToPlayDesc4: "After you choose the mode, type of game, and level of difficulty, the game begins. The passages and images are generated through the OpenAI API for that round.",
  readyTitle: "Ready",
  readyDesc: "When you understand the setup, return home and start building the room.",

  genreRiddles: "Riddles",
  genreRiddlesDesc: "Read the clue, discuss the twist, and guess the hidden answer.",
  genreGuess: "Guess",
  genreGuessDesc: "Follow the hints, weigh the obvious answer, and decide what still fits.",
  genreVisualMatch: "Visual Match",
  genreVisualMatchDesc: "Compare a 3D maze view against a labeled 2D maze map.",
  genreNumberToLetter: "Number-to-Letter Conversion",
  genreNumberToLetterDesc: "Decode the story clue and choose the answer that truly matches it.",

  diffEasy: "Easy",
  diffEasyTagline: "Clear clues and a friendly warm-up.",
  diffMedium: "Medium",
  diffMediumTagline: "Balanced twists for steady teams.",
  diffHard: "Hard",
  diffHardTagline: "Sharper traps and trickier deductions.",
  diffChallenger: "The Challenger",
  diffChallengerTagline: "The boldest version of the crown.",
};

const ko: T = {
  home: "← 홈",
  connecting: "연결 중…",
  back: "뒤로",
  close: "닫기",
  save: "저장",
  next: "다음",
  continueBtn: "계속",

  installApp: "앱 설치",
  installIosHint: "공유 → 홈 화면에 추가",
  alreadyInstalled: "설치됨 ✓",

  tagline: "왕관을 차지할 준비가 됐나요?",
  getStarted: "시작하기",
  howToPlay: "게임 방법",
  joinRoom: "방 참가",

  gameConditions: "게임 조건",
  step1Group: "1단계: 솔로 또는 그룹 플레이를 선택하고, 플레이어들을 방으로 초대하세요.",
  step1Solo: "1단계: 솔로 모드 선택 — 다른 플레이어 없이 바로 진행합니다.",
  solo: "솔로",
  group: "그룹",
  players: "플레이어",
  editParticipants: "참가자 편집",
  hostLabel: "(방장)",
  continueToGameType: "게임 유형 선택으로",

  step2: "2단계: 플레이할 게임 유형을 선택하세요.",

  step3: "3단계: 난이도를 선택하고 라운드를 시작하세요.",
  writingRound: "OpenAI로 라운드 작성 중",
  creatingImages: (done, total) => `OpenAI로 이미지 생성 중 (${done} / ${total})`,
  startGame: "게임 시작",

  passage: "지문",
  roundNotesTitle: "라운드 안내",
  note1: "이 라운드의 모든 지문과 이미지는 OpenAI API로 생성됩니다.",
  note2: "더 많은 점수를 가진 플레이어가 승리합니다.",
  note3: "힌트가 필요하면 질문하세요. 단, 1점이 차감됩니다.",
  view3d: "3D 뷰",
  maze2d: "2D 미로",
  clueKeywords: "단서 키워드",
  possibleAnswers: "가능한 답변",
  activity: "활동 내역",
  lobbyBtn: "로비",
  bonusKeywords: "보너스 키워드",
  additionalRevealed: "추가 키워드 공개",
  finalRevealed: "최종 키워드 공개",
  think: "생각",
  nextKeywordIn: "다음 키워드까지",
  bonusKeywordExcl: "보너스 키워드!",
  finalKeywordExcl: "최종 키워드!",
  giveup: "모르겠어요, 포기",

  exitGameTitle: "게임 종료",
  leaveConfirm: "정말 게임을 떠나시겠습니까?",
  stay: "계속하기",
  leaveGame: "게임 나가기",

  noWinner: "승자 없음",
  teamWins: (n) => `팀 ${n} 승리!`,
  playerWins: (name) => `${name} 승리!`,
  winner: "승자",
  newGame: "새 게임",

  joinRoomTitle: "방 참가",
  yourName: "이름",
  join: "참가",

  waitingForHost: "방장 대기 중",
  playersInRoom: (n) => `${n}명 참가 중`,
  soloMode: "솔로 모드",
  groupMode: "그룹 모드",
  hostChoosingType: "방장이 게임 유형을 선택 중…",
  hostChoosingDiff: "방장이 난이도를 선택 중…",
  selectedLabel: (name) => `선택됨: ${name}`,

  yourFeed: "내 피드",
  teamFeed: "팀 피드",
  askQuestion: "질문하기",
  questionPlaceholder: "무엇이 궁금하신가요?",
  askQuestionBtn: "질문하기 (-1점)",
  attemptAnswer: "답변 시도",
  howToAnswer: "답변 방법",
  howToAnswerLine1: "지문, 단서, 공개된 키워드를 활용해 최선의 답변을 제출하세요.",
  howToAnswerLine2: "숫자-글자 변환 및 추측 라운드에서는 보기와 신중히 비교하세요.",
  howToAnswerLine3: "비주얼 매치 라운드에서는 레이블된 미로를 참고하세요.",
  answerPlaceholder: "답변을 입력하세요",
  attemptAnswerBtn: "답변 제출",
  briefing: "상황 설명",
  pts: "점",

  scanTitle: "방 QR 코드 스캔",
  startingCamera: "카메라 시작 중…",
  pointAtQR: "호스트 화면의 QR 코드를 가리키세요",
  cameraPermissionError: "카메라 권한이 거부됐습니다. 카메라 접근을 허용하고 다시 시도해주세요.",
  cameraStartError: "카메라를 시작할 수 없습니다. HTTPS 또는 localhost인지 확인하세요.",
  orEnterCode: "또는 방 코드 입력",

  editParticipantsTitle: "참가자 편집",

  iUnderstand: "이해했습니다",
  howToPlayStep: (step, total) => `게임 방법 — ${step} / ${total}`,
  howToPlayDesc1: "혼자 플레이하거나, 온라인 플레이어와 함께 하거나, 그룹으로 플레이할 수 있습니다. 모드 선택 단계입니다.",
  soloCardTitle: "솔로",
  soloCardDesc: "혼자서 왕관을 향해 도전하세요.",
  groupCardTitle: "그룹",
  groupCardDesc: "함께 토론하며 단서를 가장 잘 읽는 사람을 찾으세요.",
  howToPlayDesc2: "다음으로 플레이할 게임 유형을 선택합니다: 수수께끼, 추측, 비주얼 미로 매칭, 숫자-글자 변환 등.",
  howToPlayDesc3: "이후 난이도를 선택합니다: 쉬움, 보통, 어려움, 또는 챌린저.",
  morePts: "더 많은 점수를 가진 플레이어가 승리합니다.",
  howToPlayDesc4: "모드, 게임 유형, 난이도를 선택하면 게임이 시작됩니다. 지문과 이미지는 해당 라운드를 위해 OpenAI API로 생성됩니다.",
  readyTitle: "준비 완료",
  readyDesc: "설정을 이해했다면 홈으로 돌아가서 방을 만드세요.",

  genreRiddles: "수수께끼",
  genreRiddlesDesc: "단서를 읽고 반전을 토론하며 숨겨진 답을 맞추세요.",
  genreGuess: "추측",
  genreGuessDesc: "힌트를 따라가며 가장 적합한 답을 결정하세요.",
  genreVisualMatch: "비주얼 매치",
  genreVisualMatchDesc: "3D 미로 뷰와 레이블된 2D 미로 맵을 비교하세요.",
  genreNumberToLetter: "숫자-글자 변환",
  genreNumberToLetterDesc: "스토리 단서를 해석하고 진짜 답을 고르세요.",

  diffEasy: "쉬움",
  diffEasyTagline: "명확한 단서와 친근한 워밍업.",
  diffMedium: "보통",
  diffMediumTagline: "균형 잡힌 반전으로 안정적인 팀에 적합.",
  diffHard: "어려움",
  diffHardTagline: "더 날카로운 함정과 복잡한 추리.",
  diffChallenger: "챌린저",
  diffChallengerTagline: "왕관의 가장 도전적인 버전.",
};

const vi: T = {
  home: "← Trang chủ",
  connecting: "Đang kết nối…",
  back: "Quay lại",
  close: "Đóng",
  save: "Lưu",
  next: "Tiếp theo",
  continueBtn: "Tiếp tục",

  installApp: "Cài đặt ứng dụng",
  installIosHint: "Nhấn Chia sẻ → Thêm vào màn hình chính",
  alreadyInstalled: "Đã cài đặt ✓",

  tagline: "Ai sẵn sàng giành vương miện?",
  getStarted: "Bắt đầu",
  howToPlay: "Cách chơi",
  joinRoom: "Tham gia phòng",

  gameConditions: "Điều kiện trò chơi",
  step1Group: "Bước 1: chọn chế độ solo hay nhóm, rồi mời người chơi vào phòng.",
  step1Solo: "Bước 1: đã chọn chế độ solo — không cần người chơi khác. Tiếp tục chọn loại trò chơi.",
  solo: "Solo",
  group: "Nhóm",
  players: "Người chơi",
  editParticipants: "Sửa người tham gia",
  hostLabel: "(chủ phòng)",
  continueToGameType: "Tiếp tục chọn loại trò chơi",

  step2: "Bước 2: chọn loại trò chơi bạn muốn chơi.",

  step3: "Bước 3: chọn độ khó, rồi bắt đầu vòng đấu.",
  writingRound: "Đang soạn vòng đấu với OpenAI",
  creatingImages: (done, total) => `Đang tạo hình ảnh với OpenAI (${done} / ${total})`,
  startGame: "Bắt đầu trò chơi",

  passage: "Đoạn văn",
  roundNotesTitle: "Lưu ý vòng đấu",
  note1: "Tất cả đoạn văn và hình ảnh trong vòng này được tạo bởi OpenAI API.",
  note2: "Người có nhiều điểm hơn sẽ thắng.",
  note3: "Hỏi để lấy gợi ý, nhưng mỗi câu hỏi tốn 1 điểm.",
  view3d: "Góc nhìn 3D",
  maze2d: "Mê cung 2D",
  clueKeywords: "Từ khóa gợi ý",
  possibleAnswers: "Đáp án có thể",
  activity: "Hoạt động",
  lobbyBtn: "Sảnh",
  bonusKeywords: "Từ khóa thưởng",
  additionalRevealed: "Từ khóa bổ sung đã được tiết lộ",
  finalRevealed: "Từ khóa cuối đã được tiết lộ",
  think: "Suy nghĩ",
  nextKeywordIn: "Từ khóa tiếp theo sau",
  bonusKeywordExcl: "Từ khóa thưởng!",
  finalKeywordExcl: "Từ khóa cuối!",
  giveup: "Tôi không biết, bỏ cuộc",

  exitGameTitle: "Thoát trò chơi",
  leaveConfirm: "Bạn có chắc muốn rời trò chơi không?",
  stay: "Ở lại",
  leaveGame: "Rời trò chơi",

  noWinner: "Không có người thắng",
  teamWins: (n) => `Đội ${n} thắng!`,
  playerWins: (name) => `${name} thắng!`,
  winner: "Người thắng",
  newGame: "Trò chơi mới",

  joinRoomTitle: "Tham gia phòng",
  yourName: "Tên của bạn",
  join: "Tham gia",

  waitingForHost: "Đang chờ chủ phòng",
  playersInRoom: (n) => `${n} người trong phòng`,
  soloMode: "Chế độ solo",
  groupMode: "Chế độ nhóm",
  hostChoosingType: "Chủ phòng đang chọn loại trò chơi…",
  hostChoosingDiff: "Chủ phòng đang chọn độ khó…",
  selectedLabel: (name) => `Đã chọn: ${name}`,

  yourFeed: "Bảng tin của bạn",
  teamFeed: "Bảng tin nhóm",
  askQuestion: "Đặt câu hỏi",
  questionPlaceholder: "Bạn muốn biết điều gì?",
  askQuestionBtn: "Đặt câu hỏi (-1 điểm)",
  attemptAnswer: "Thử trả lời",
  howToAnswer: "Cách trả lời",
  howToAnswerLine1: "Đưa ra câu trả lời tốt nhất dựa trên đoạn văn, gợi ý và từ khóa đã được tiết lộ.",
  howToAnswerLine2: "Với vòng chuyển đổi số-chữ và đoán, hãy so sánh kỹ với các lựa chọn.",
  howToAnswerLine3: "Với vòng khớp hình ảnh, dùng mê cung có nhãn để hỗ trợ quyết định.",
  answerPlaceholder: "Nhập câu trả lời bạn muốn gửi",
  attemptAnswerBtn: "Gửi câu trả lời",
  briefing: "Tình huống",
  pts: "điểm",

  scanTitle: "Quét mã QR phòng",
  startingCamera: "Đang khởi động camera…",
  pointAtQR: "Hướng vào mã QR trên màn hình chủ phòng",
  cameraPermissionError: "Quyền camera bị từ chối. Vui lòng cho phép truy cập camera và thử lại.",
  cameraStartError: "Không thể khởi động camera. Đảm bảo bạn đang dùng HTTPS hoặc localhost.",
  orEnterCode: "Hoặc nhập mã phòng",

  editParticipantsTitle: "Sửa người tham gia",

  iUnderstand: "Tôi hiểu rồi",
  howToPlayStep: (step, total) => `Cách chơi — ${step} / ${total}`,
  howToPlayDesc1: "Bạn có thể chơi một mình, ghép với AI hoặc người chơi trực tuyến, hoặc chơi theo nhóm. Đây là bước chọn chế độ.",
  soloCardTitle: "Solo",
  soloCardDesc: "Một mình truy đuổi vương miện theo nhịp của bạn.",
  groupCardTitle: "Nhóm",
  groupCardDesc: "Cùng thảo luận và xem ai đọc gợi ý tốt nhất.",
  howToPlayDesc2: "Tiếp theo, chọn loại trò chơi: câu đố, đoán, khớp mê cung hình ảnh, chuyển đổi số-chữ, v.v.",
  howToPlayDesc3: "Sau đó chọn mức độ thách thức: dễ, trung bình, khó, hoặc thách đấu.",
  morePts: "Người có nhiều điểm hơn sẽ thắng.",
  howToPlayDesc4: "Sau khi chọn chế độ, loại trò chơi và độ khó, trò chơi bắt đầu. Các đoạn văn và hình ảnh được tạo bởi OpenAI API cho mỗi vòng.",
  readyTitle: "Sẵn sàng",
  readyDesc: "Khi đã hiểu cách chơi, quay về trang chủ và tạo phòng.",

  genreRiddles: "Câu đố",
  genreRiddlesDesc: "Đọc gợi ý, thảo luận về tình tiết, và đoán câu trả lời ẩn.",
  genreGuess: "Đoán",
  genreGuessDesc: "Theo dõi gợi ý, cân nhắc câu trả lời rõ ràng và quyết định cái nào phù hợp.",
  genreVisualMatch: "Khớp hình ảnh",
  genreVisualMatchDesc: "So sánh góc nhìn mê cung 3D với bản đồ mê cung 2D có nhãn.",
  genreNumberToLetter: "Chuyển đổi số-chữ",
  genreNumberToLetterDesc: "Giải mã gợi ý câu chuyện và chọn câu trả lời thực sự phù hợp.",

  diffEasy: "Dễ",
  diffEasyTagline: "Gợi ý rõ ràng và khởi động thân thiện.",
  diffMedium: "Trung bình",
  diffMediumTagline: "Tình tiết cân bằng cho các nhóm ổn định.",
  diffHard: "Khó",
  diffHardTagline: "Bẫy sắc bén hơn và suy luận phức tạp hơn.",
  diffChallenger: "Thách đấu",
  diffChallengerTagline: "Phiên bản táo bạo nhất của vương miện.",
};

const fr: T = {
  home: "← Accueil",
  connecting: "Connexion…",
  back: "Retour",
  close: "Fermer",
  save: "Enregistrer",
  next: "Suivant",
  continueBtn: "Continuer",

  installApp: "Installer l'application",
  installIosHint: "Partager → Sur l'écran d'accueil",
  alreadyInstalled: "Installée ✓",

  tagline: "Qui est prêt à prendre la couronne ?",
  getStarted: "Commencer",
  howToPlay: "Comment jouer",
  joinRoom: "Rejoindre une salle",

  gameConditions: "Conditions de jeu",
  step1Group: "Étape 1 : choisissez solo ou groupe, puis invitez des joueurs dans la salle.",
  step1Solo: "Étape 1 : mode solo sélectionné — pas d'autres joueurs nécessaires. Passez au type de jeu.",
  solo: "Solo",
  group: "Groupe",
  players: "Joueurs",
  editParticipants: "Modifier les participants",
  hostLabel: "(hôte)",
  continueToGameType: "Continuer vers le type de jeu",

  step2: "Étape 2 : choisissez le type de jeu.",

  step3: "Étape 3 : choisissez le niveau de difficulté, puis démarrez.",
  writingRound: "Rédaction de la manche avec OpenAI",
  creatingImages: (done, total) => `Création des images avec OpenAI (${done} / ${total})`,
  startGame: "Démarrer le jeu",

  passage: "Passage",
  roundNotesTitle: "Notes de manche",
  note1: "Tous les passages et images sont générés par l'API OpenAI.",
  note2: "Celui qui a le plus de points gagne.",
  note3: "Posez une question pour un indice, mais cela coûte 1 point.",
  view3d: "Vue 3D",
  maze2d: "Labyrinthe 2D",
  clueKeywords: "Mots-clés indices",
  possibleAnswers: "Réponses possibles",
  activity: "Activité",
  lobbyBtn: "Lobby",
  bonusKeywords: "Mots-clés bonus",
  additionalRevealed: "Mot-clé supplémentaire révélé",
  finalRevealed: "Mot-clé final révélé",
  think: "Réflexion",
  nextKeywordIn: "Prochain mot-clé dans",
  bonusKeywordExcl: "Mot-clé bonus !",
  finalKeywordExcl: "Mot-clé final !",
  giveup: "Je n'ai aucune idée, j'abandonne",

  exitGameTitle: "Quitter le jeu",
  leaveConfirm: "Voulez-vous vraiment quitter le jeu ?",
  stay: "Rester",
  leaveGame: "Quitter le jeu",

  noWinner: "Pas de gagnant",
  teamWins: (n) => `L'équipe ${n} gagne !`,
  playerWins: (name) => `${name} gagne !`,
  winner: "Gagnant",
  newGame: "Nouveau jeu",

  joinRoomTitle: "Rejoindre la salle",
  yourName: "Votre nom",
  join: "Rejoindre",

  waitingForHost: "En attente de l'hôte",
  playersInRoom: (n) => `${n} joueurs dans la salle`,
  soloMode: "Mode solo",
  groupMode: "Mode groupe",
  hostChoosingType: "L'hôte choisit le type de jeu…",
  hostChoosingDiff: "L'hôte choisit la difficulté…",
  selectedLabel: (name) => `Sélectionné : ${name}`,

  yourFeed: "Votre fil",
  teamFeed: "Fil d'équipe",
  askQuestion: "Poser une question",
  questionPlaceholder: "Que voulez-vous savoir ?",
  askQuestionBtn: "Poser une question (-1 pt)",
  attemptAnswer: "Tenter une réponse",
  howToAnswer: "Comment répondre",
  howToAnswerLine1: "Donnez votre meilleure réponse en utilisant le passage, les indices et les mots-clés révélés.",
  howToAnswerLine2: "Pour les manches chiffres-lettres et devinettes, comparez avec les choix.",
  howToAnswerLine3: "Pour les manches visual-match, utilisez le labyrinthe étiqueté.",
  answerPlaceholder: "Tapez la réponse à soumettre",
  attemptAnswerBtn: "Soumettre la réponse",
  briefing: "Briefing",
  pts: "pts",

  scanTitle: "Scanner le QR de la salle",
  startingCamera: "Démarrage de la caméra…",
  pointAtQR: "Pointez vers le QR sur l'écran de l'hôte",
  cameraPermissionError: "Permission caméra refusée. Autorisez l'accès à la caméra et réessayez.",
  cameraStartError: "Impossible de démarrer la caméra. Vérifiez que vous êtes en HTTPS ou localhost.",
  orEnterCode: "Ou entrez le code de salle",

  editParticipantsTitle: "Modifier les participants",

  iUnderstand: "J'ai compris",
  howToPlayStep: (step, total) => `Comment jouer — ${step} / ${total}`,
  howToPlayDesc1: "Vous pouvez jouer seul, avec des joueurs en ligne, ou en groupe. C'est l'étape de sélection du mode.",
  soloCardTitle: "Solo",
  soloCardDesc: "Seul, partez à la conquête de la couronne à votre rythme.",
  groupCardTitle: "Groupe",
  groupCardDesc: "Discutez ensemble et voyez qui lit le mieux les indices.",
  howToPlayDesc2: "Ensuite, choisissez le type de jeu : énigmes, devinettes, labyrinthe visuel, conversion chiffres-lettres, etc.",
  howToPlayDesc3: "Puis choisissez le niveau de défi : facile, moyen, difficile ou challenger.",
  morePts: "Celui qui a le plus de points gagne.",
  howToPlayDesc4: "Après avoir choisi le mode, le type de jeu et la difficulté, le jeu commence. Les passages et images sont générés par l'API OpenAI.",
  readyTitle: "Prêt",
  readyDesc: "Quand vous comprenez la configuration, revenez à l'accueil pour créer la salle.",

  genreRiddles: "Énigmes",
  genreRiddlesDesc: "Lisez l'indice, discutez du twist et devinez la réponse cachée.",
  genreGuess: "Devinette",
  genreGuessDesc: "Suivez les indices, pesez la réponse évidente et décidez ce qui convient.",
  genreVisualMatch: "Correspondance visuelle",
  genreVisualMatchDesc: "Comparez une vue de labyrinthe 3D avec une carte de labyrinthe 2D étiquetée.",
  genreNumberToLetter: "Conversion chiffres-lettres",
  genreNumberToLetterDesc: "Décodez l'indice narratif et choisissez la réponse qui correspond vraiment.",

  diffEasy: "Facile",
  diffEasyTagline: "Des indices clairs pour une mise en route amicale.",
  diffMedium: "Moyen",
  diffMediumTagline: "Des rebondissements équilibrés pour des équipes stables.",
  diffHard: "Difficile",
  diffHardTagline: "Des pièges plus affûtés et des déductions plus complexes.",
  diffChallenger: "Le Challenger",
  diffChallengerTagline: "La version la plus audacieuse de la couronne.",
};

const hi: T = {
  home: "← होम",
  connecting: "कनेक्ट हो रहे हैं…",
  back: "वापस",
  close: "बंद करें",
  save: "सहेजें",
  next: "अगला",
  continueBtn: "जारी रखें",

  installApp: "ऐप इंस्टॉल करें",
  installIosHint: "शेयर → होम स्क्रीन पर जोड़ें",
  alreadyInstalled: "इंस्टॉल हो गया ✓",

  tagline: "ताज जीतने के लिए कौन तैयार है?",
  getStarted: "शुरू करें",
  howToPlay: "कैसे खेलें",
  joinRoom: "कमरे में शामिल हों",

  gameConditions: "खेल की शर्तें",
  step1Group: "चरण 1: सोलो या ग्रुप मोड चुनें, फिर खिलाड़ियों को कमरे में आमंत्रित करें।",
  step1Solo: "चरण 1: सोलो मोड चुना गया — कोई अन्य खिलाड़ी नहीं चाहिए। गेम टाइप चुनें।",
  solo: "सोलो",
  group: "ग्रुप",
  players: "खिलाड़ी",
  editParticipants: "प्रतिभागी संपादित करें",
  hostLabel: "(होस्ट)",
  continueToGameType: "गेम टाइप पर जाएं",

  step2: "चरण 2: जो गेम खेलना है उसका प्रकार चुनें।",

  step3: "चरण 3: कठिनाई स्तर चुनें, फिर राउंड शुरू करें।",
  writingRound: "OpenAI से राउंड लिखा जा रहा है",
  creatingImages: (done, total) => `OpenAI से छवियां बनाई जा रही हैं (${done} / ${total})`,
  startGame: "खेल शुरू करें",

  passage: "अनुच्छेद",
  roundNotesTitle: "राउंड नोट्स",
  note1: "इस राउंड के सभी अनुच्छेद और छवियां OpenAI API से बनाई गई हैं।",
  note2: "जिसके ज़्यादा अंक हों, वह जीतता है।",
  note3: "संकेत के लिए सवाल पूछें, लेकिन इसमें 1 अंक लगता है।",
  view3d: "3D व्यू",
  maze2d: "2D भूलभुलैया",
  clueKeywords: "संकेत कीवर्ड",
  possibleAnswers: "संभावित उत्तर",
  activity: "गतिविधि",
  lobbyBtn: "लॉबी",
  bonusKeywords: "बोनस कीवर्ड",
  additionalRevealed: "अतिरिक्त कीवर्ड उजागर हुआ",
  finalRevealed: "अंतिम कीवर्ड उजागर हुआ",
  think: "सोचें",
  nextKeywordIn: "अगला कीवर्ड",
  bonusKeywordExcl: "बोनस कीवर्ड!",
  finalKeywordExcl: "अंतिम कीवर्ड!",
  giveup: "मुझे नहीं पता, हार मान लेता हूं",

  exitGameTitle: "गेम से बाहर",
  leaveConfirm: "क्या आप सच में गेम छोड़ना चाहते हैं?",
  stay: "रुकें",
  leaveGame: "गेम छोड़ें",

  noWinner: "कोई विजेता नहीं",
  teamWins: (n) => `टीम ${n} जीती!`,
  playerWins: (name) => `${name} जीते!`,
  winner: "विजेता",
  newGame: "नया खेल",

  joinRoomTitle: "कमरे में शामिल हों",
  yourName: "आपका नाम",
  join: "शामिल हों",

  waitingForHost: "होस्ट का इंतज़ार",
  playersInRoom: (n) => `${n} खिलाड़ी कमरे में`,
  soloMode: "सोलो मोड",
  groupMode: "ग्रुप मोड",
  hostChoosingType: "होस्ट गेम टाइप चुन रहे हैं…",
  hostChoosingDiff: "होस्ट कठिनाई चुन रहे हैं…",
  selectedLabel: (name) => `चुना गया: ${name}`,

  yourFeed: "आपका फ़ीड",
  teamFeed: "टीम फ़ीड",
  askQuestion: "सवाल पूछें",
  questionPlaceholder: "आप क्या जानना चाहते हैं?",
  askQuestionBtn: "सवाल पूछें (-1 अंक)",
  attemptAnswer: "उत्तर का प्रयास",
  howToAnswer: "उत्तर कैसे दें",
  howToAnswerLine1: "अनुच्छेद, संकेत और उजागर कीवर्ड का उपयोग करके सर्वश्रेष्ठ उत्तर दें।",
  howToAnswerLine2: "संख्या-अक्षर और अनुमान राउंड में विकल्पों से ध्यान से तुलना करें।",
  howToAnswerLine3: "विज़ुअल मैच राउंड में लेबल वाली भूलभुलैया का उपयोग करें।",
  answerPlaceholder: "जो उत्तर देना है वह टाइप करें",
  attemptAnswerBtn: "उत्तर जमा करें",
  briefing: "ब्रीफिंग",
  pts: "अंक",

  scanTitle: "कमरे का QR कोड स्कैन करें",
  startingCamera: "कैमरा शुरू हो रहा है…",
  pointAtQR: "होस्ट स्क्रीन के QR कोड की ओर इशारा करें",
  cameraPermissionError: "कैमरा अनुमति अस्वीकृत। कृपया कैमरा एक्सेस की अनुमति दें और पुनः प्रयास करें।",
  cameraStartError: "कैमरा शुरू नहीं हो सका। सुनिश्चित करें कि आप HTTPS या localhost पर हैं।",
  orEnterCode: "या कमरे का कोड दर्ज करें",

  editParticipantsTitle: "प्रतिभागी संपादित करें",

  iUnderstand: "मैं समझ गया",
  howToPlayStep: (step, total) => `कैसे खेलें — ${step} / ${total}`,
  howToPlayDesc1: "आप अकेले, AI या ऑनलाइन खिलाड़ियों के साथ, या ग्रुप में खेल सकते हैं। यह मोड चयन का चरण है।",
  soloCardTitle: "सोलो",
  soloCardDesc: "अकेले ताज की तलाश में जाएं।",
  groupCardTitle: "ग्रुप",
  groupCardDesc: "मिलकर चर्चा करें और देखें कौन संकेत सबसे अच्छे पढ़ता है।",
  howToPlayDesc2: "फिर गेम का प्रकार चुनें: पहेलियां, अनुमान, विज़ुअल भूलभुलैया, संख्या-अक्षर रूपांतरण, आदि।",
  howToPlayDesc3: "उसके बाद चुनौती का स्तर चुनें: आसान, मध्यम, कठिन, या चैलेंजर।",
  morePts: "जिसके ज़्यादा अंक हों, वह जीतता है।",
  howToPlayDesc4: "मोड, गेम टाइप और कठिनाई चुनने के बाद, खेल शुरू हो जाता है। अनुच्छेद और छवियां उस राउंड के लिए OpenAI API से बनाई जाती हैं।",
  readyTitle: "तैयार",
  readyDesc: "जब आप सेटअप समझ लें, तो होम पर वापस जाएं और कमरा बनाएं।",

  genreRiddles: "पहेलियां",
  genreRiddlesDesc: "संकेत पढ़ें, मोड़ पर चर्चा करें, और छिपा उत्तर ढूंढें।",
  genreGuess: "अनुमान",
  genreGuessDesc: "संकेतों का अनुसरण करें, स्पष्ट उत्तर तौलें, और तय करें क्या फिट बैठता है।",
  genreVisualMatch: "विज़ुअल मैच",
  genreVisualMatchDesc: "3D भूलभुलैया दृश्य को लेबल वाले 2D मानचित्र से मिलाएं।",
  genreNumberToLetter: "संख्या-अक्षर रूपांतरण",
  genreNumberToLetterDesc: "कहानी संकेत को डीकोड करें और सही उत्तर चुनें।",

  diffEasy: "आसान",
  diffEasyTagline: "स्पष्ट संकेत और सहज शुरुआत।",
  diffMedium: "मध्यम",
  diffMediumTagline: "स्थिर टीमों के लिए संतुलित चुनौतियां।",
  diffHard: "कठिन",
  diffHardTagline: "तेज़ जाल और जटिल तर्क।",
  diffChallenger: "चैलेंजर",
  diffChallengerTagline: "ताज का सबसे साहसी संस्करण।",
};

export const translations: Record<Locale, T> = { en, ko, vi, fr, hi };

// Maps the English genre name (stored in room.genre) to translated display name + description.
export function getGenreDisplay(name: string, t: T): { name: string; description: string } {
  const map: Record<string, { name: string; description: string }> = {
    Riddles: { name: t.genreRiddles, description: t.genreRiddlesDesc },
    Guess: { name: t.genreGuess, description: t.genreGuessDesc },
    "Visual Match": { name: t.genreVisualMatch, description: t.genreVisualMatchDesc },
    "Number-to-Letter Conversion": { name: t.genreNumberToLetter, description: t.genreNumberToLetterDesc },
  };
  return map[name] ?? { name, description: "" };
}

// Maps the English difficulty value to translated label + tagline.
export function getDifficultyDisplay(value: string, t: T): { label: string; tagline: string } {
  const map: Record<string, { label: string; tagline: string }> = {
    easy: { label: t.diffEasy, tagline: t.diffEasyTagline },
    medium: { label: t.diffMedium, tagline: t.diffMediumTagline },
    hard: { label: t.diffHard, tagline: t.diffHardTagline },
    challenger: { label: t.diffChallenger, tagline: t.diffChallengerTagline },
  };
  return map[value] ?? { label: value, tagline: "" };
}
